"use strict";

// Re-export professions for backwards compatibility
export { PROFESSIONS } from './Professions.js';

export const TILE_DEFINITIONS = {
    streamline: [
        { name: "義工卡",     type: "volunteer" },
        { name: "騙子卡",     type: "lier" },
        { name: "察覺卡",     type: "awareness" },
        { name: "機會卡",     type: "opportunity" },
        { name: "結算日",     type: "settlement" },
        { name: "機會卡",     type: "opportunity" },
        { name: "逆流層入口", type: "reverse_entry" },
        { name: "機會卡",     type: "opportunity" },
        { name: "幸運星",     type: "lucky_star" },
        { name: "機會卡",     type: "opportunity" },
        { name: "察覺卡",     type: "awareness" },
        { name: "機會卡",     type: "opportunity" },
        { name: "結算日",     type: "settlement" },
        { name: "警察卡",     type: "police" },
        { name: "察覺卡",     type: "awareness" },
        { name: "機會卡",     type: "opportunity" },
        { name: "四葉草",     type: "four_leaf_clover" },
        { name: "機會卡",     type: "opportunity" },
        { name: "逆流層出口", type: "reverse_exit" },
        { name: "機會卡",     type: "opportunity" },
        { name: "結算日",     type: "settlement" },
        { name: "機會卡",     type: "opportunity" },
        { name: "察覺卡",     type: "awareness" },
        { name: "機會卡",     type: "opportunity" }
    ],
    reverse: [
        { name: "覺察卡",     type: "awareness" },
        { name: "逆境自強卡", type: "hardship" },
        { name: "覺察卡",     type: "awareness" },
        { name: "生意失敗",   type: "business_failure" },
        { name: "奇蹟",       type: "miracle" },
        { name: "失業",       type: "unemployment" },
        { name: "覺察卡",     type: "awareness" },
        { name: "逆境自強卡", type: "hardship" },
        { name: "覺察卡",     type: "awareness" }
    ],
    flow: [
        { name: "資產信託",     type: "asset_trust" },
        { name: "訂制夢想跑車", type: "dream",            needEnergy: 50 },
        { name: "項目投資",     type: "investment_tile" },
        { name: "私人島嶼",     type: "dream",            needEnergy: 40 },
        { name: "社会服务中心", type: "social_service" },
        { name: "登頂富士山",   type: "dream" },
        { name: "項目投資",     type: "investment_tile" },
        { name: "夢想",         type: "dream" },
        { name: "查稅審計",     type: "audit" },
        { name: "夢想",         type: "dream" },
        { name: "項目投資",     type: "investment_tile" },
        { name: "夢想",         type: "dream" },
        { name: "結算日",       type: "settlement" },
        { name: "社会服务中心", type: "social_service" },
        { name: "項目投資",     type: "investment_tile" },
        { name: "夢想",         type: "dream" },
        { name: "破產",         type: "flowbankruptcy" },
        { name: "夢想",         type: "dream" },
        { name: "項目投資",     type: "investment_tile" },
        { name: "夢想",         type: "dream" },
        { name: "社会服务中心", type: "social_service" },
        { name: "夢想",         type: "dream" },
        { name: "項目投資",     type: "investment_tile" },
        { name: "夢想",         type: "dream" },
        { name: "生意失敗",     type: "business_failure" },
        { name: "夢想",         type: "dream" },
        { name: "項目投資",     type: "investment_tile" },
        { name: "夢想",         type: "dream" },
        { name: "結算日",       type: "settlement" },
        { name: "社会服务中心", type: "social_service" },
        { name: "項目投資",     type: "investment_tile" },
        { name: "夢想",         type: "dream" }
    ]
};