"use strict";

// Re-export professions for backwards compatibility
export { PROFESSIONS } from './Professions.js';

export const TILE_DEFINITIONS = {
    streamline: [
        { name: "義工卡",     type: "volunteer" },
        { name: "騙子卡",     type: "lier" },
        { name: "察覺卡",     type: "awareness" },
        { name: "機會卡",     type: "opportunity" },
        { name: "結算日",     type: "opportunity" },
        { name: "機會卡",     type: "opportunity" },
        { name: "逆流層入口", type: "opportunity" },
        { name: "機會卡",     type: "opportunity" },
        { name: "幸運星",     type: "lucky_star" },
        { name: "機會卡",     type: "opportunity" },
        { name: "察覺卡",     type: "awareness" },
        { name: "機會卡",     type: "opportunity" },
        { name: "結算日",     type: "settlement" },
        { name: "警察卡",     type: "police" },
        { name: "察覺卡",     type: "awareness" },
        { name: "機會卡",     type: "opportunity" },
        { name: "四葉草",     type: "four_leaf_clover" },
        { name: "機會卡",     type: "opportunity" },
        { name: "逆流層出口", type: "reverse_exit" },
        { name: "機會卡",     type: "opportunity" },
        { name: "結算日",     type: "settlement" },
        { name: "機會卡",     type: "opportunity" },
        { name: "察覺卡",     type: "awareness" },
        { name: "機會卡",     type: "opportunity" }
    ],
    reverse: [
        { name: "覺察卡",     type: "awareness" },
        { name: "逆境自強卡", type: "hardship" },
        { name: "覺察卡",     type: "awareness" },
        { name: "生意失敗",   type: "business_failure" },
        { name: "奇蹟",       type: "miracle" },
        { name: "失業",       type: "unemployment" },
        { name: "覺察卡",     type: "awareness" },
        { name: "逆境自強卡", type: "hardship" },
        { name: "覺察卡",     type: "awareness" }
    ],
    flow: [
        { name: "資產信託",     type: "asset_trust" },
        { name: "訂制夢想跑車", type: "dream",            needEnergy: 50 },
        { name: "項目投資",     type: "investment_tile" },
        { name: "競投名畫",     type: "dream"},
        { name: "社會服務中心", type: "social_service" },
        { name: "登頂富士山",   type: "dream",            needEnergy: 30},
        { name: "項目投資",     type: "investment_tile" },
        { name: "開設媒體平台",         type: "dream", needEnergy: 40},
        { name: "查稅審計",     type: "audit" },
        { name: "舉辦大型演唱會",         type: "dream", needEnergy: 40},
        { name: "項目投資",     type: "investment_tile" },
        { name: "極限運動",         type: "dream", needEnergy: 30 },
        { name: "結算日",       type: "settlement" },
        { name: "社會服務中心", type: "social_service" },
        { name: "項目投資",     type: "investment_tile" },
        { name: "深海探險",         type: "dream" , needEnergy: 100},
        { name: "破產",         type: "flowbankruptcy" },
        { name: "按自己興趣開店",         type: "dream", needEnergy: 50},
        { name: "項目投資",     type: "investment_tile" },
        { name: "非洲探險",         type: "dream", needEnergy: 10},
        { name: "社會服務中心", type: "social_service" },
        { name: "購買豪宅",         type: "dream", needEnergy: 50},
        { name: "項目投資",     type: "investment_tile" },
        { name: "投資拍電影",         type: "dream", needEnergy: 30},
        { name: "生意失敗",     type: "business_failure" },
        { name: "和股神食飯",         type: "dream", needEnergy: 20 },
        { name: "項目投資",     type: "investment_tile" },
        { name: "購買私人莊園",         type: "dream", needEnergy: 50 },
        { name: "結算日",       type: "settlement" },
        { name: "社會服務中心", type: "social_service" },
        { name: "項目投資",     type: "investment_tile" },
        { name: "環遊世界",         type: "dream", needEnergy: 30 }
    ]
};